name: ai-trpg
channels:
  - conda-forge
  - defaults
dependencies:
  # Python runtime (required version)
  - python>=3.8,<3.12
  
  # Core dependencies
  - requests>=2.31.0
  
  # Development and optional tools
  - pip
  
  # Optional: Jupyter for development and testing
  # - jupyter
  # - ipykernel
  
  # Pip-only dependencies (when RAG functionality is added)
  - pip:
    # Uncomment when implementing RAG features:
    # - lightrag>=0.1.0
    # - chromadb>=0.4.0
    # - sentence-transformers>=2.2.0
    
# Environment variables (optional)
variables:
  # Set default config path
  TRPG_CONFIG_PATH: "config/game_config.json"
  # Set default log level
  TRPG_LOG_LEVEL: "INFO"
  
# Usage:
# conda env create -f environment.yaml
# conda activate ai-trpg
# python main.py --help